#!/bin/bash
echo "ahahahahahahahahahahahahhahahhahahahahahahahahahahahahahahahahahahahahahhaahahahahahahahhahahahahahahahhahahahahahahahahahhahahahahhahahhahahahahahahahahhahahahahahahhahahahahahhahahhahahahhahhahahahahahahahahahahhaahahahhahahahahahhahahahahahhahahahahhahahahhahaha...haha.ha...you found nothing" 
